// flow-typed signature: b505d7e9fb0623aec11a7491b5d7b6f0
// flow-typed version: <<STUB>>/redux-persist-state-manager_v^0.1.1/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-persist-state-manager'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-persist-state-manager' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-persist-state-manager/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-persist-state-manager/lib/index.js' {
  declare module.exports: $Exports<'redux-persist-state-manager/lib/index'>;
}
