// flow-typed signature: d579aa5170ee87c4b9f7a39151d90424
// flow-typed version: <<STUB>>/shitty-qs_v^1.0.1/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'shitty-qs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'shitty-qs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'shitty-qs/perf-test' {
  declare module.exports: any;
}

declare module 'shitty-qs/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'shitty-qs/index' {
  declare module.exports: $Exports<'shitty-qs'>;
}
declare module 'shitty-qs/index.js' {
  declare module.exports: $Exports<'shitty-qs'>;
}
declare module 'shitty-qs/perf-test.js' {
  declare module.exports: $Exports<'shitty-qs/perf-test'>;
}
declare module 'shitty-qs/test.js' {
  declare module.exports: $Exports<'shitty-qs/test'>;
}
