//@flow

// Actions
export const LOGOUT = 'Logout'

// Titles
export const ACTIVATION_METHOD = 'Activation Method'
export const ADDRESS = 'Address'
export const ACCESS_KEYS = 'Access Keys'
export const APP_KEY = 'App Key'
export const APP_SESSION_KEY = 'App Session Key'
export const APPLICATION = 'Application'
export const APPLICATION_EUI = 'Application EUI'
export const APPLICATION_ID = 'Application ID'
export const APPLICATION_OVERVIEW = 'Application Overview'
export const AUTOMATICALLY_UPDATE_GATEWAY = 'Automatically update gateway'
export const CANCEL = 'Cancel'
export const CAUTION = 'Caution'
export const COLLABORATOR = 'Collaborator'
export const COLLABORATORS = 'Collaborators'
export const DELETE = 'Delete'
export const DEVICE = 'Device'
export const DEVICES = 'Devices'
export const DESCRIPTION = 'Description'
export const DEVICE_ADDRESS = 'Device Address'
export const DEVICE_EUI = 'Device EUI'
export const DEVICE_ID = 'Device ID'
export const DEVICE_OVERVIEW = 'Device Overview'
export const EUIS = 'EUIs'
export const FRAME_COUNTER_CHECKS = 'Frame Counter Checks'
export const FRAME_COUNTER_WIDTH = 'Frame Counter Width'
export const FREQUENCY_PLAN = 'Frequency plan'
export const GATEWAY = 'Gateway'
export const GATEWAY_OVERVIEW = 'Gateway Overview'
export const GENERAL = 'General'
export const INFORMATION = 'Information'
export const KEYS = 'Keys'
export const LOCATION = 'Location'
export const METADATA = 'Metadata'
export const NETWORK_SESSION_KEY = 'Network Session Key'
export const REMOVE = 'Remove'
export const RIGHTS = 'Rights'
export const ROUTER = 'Router'
export const SAVE = 'Save'
export const SETTINGS = 'Settings'
export const STATUS = 'Status'
export const FRAMES_UP = 'Frames up'
export const FRAMES_DOWN = 'Frames down'

// Messages
export const ABP_KEYS_GENERATED =
  'Device Address, Network Session Key & App Session Key will be generated'
export const APP_ID_ALREADY_REGISTERED = 'Application ID already registered'
export const AUTOMATICALLY_UPDATE_GATEWAY_WARNING =
  'Enabling auto updates may cause your gateway to have unexpected downtime when updating'
export const CONFIRM_DELETE = 'Are you sure you want to delete'
export const CONFIRM_REMOVE = 'Are you sure you want to remove'
export const DEVICE_ID_ALREADY_REGISTERED = 'Device ID already registered'
export const EDIT_COLLABORATOR = 'Edit collaborator'
export const FRAME_COUNTER_CHECK_WARNING =
  'Disabling frame counter checks drastically reduces security and should only be used for development purposes'
export const FROM = 'from'
export const RIGHT_DESCRIPTION_COLLABORATORS =
  'Edit the application collaborators'
export const RIGHT_DESCRIPTION_DELETE = 'Delete the application'
export const RIGHT_DESCRIPTION_DEVICES =
  'View and edit devices of the application'
export const RIGHT_DESCRIPTION_SETTINGS =
  'Manage the application settings & access keys'
export const NEVER_SEEN = 'never seen'
export const NOT_FOUND = 'not found'
export const OPTIONAL = 'optional'
export const REMOVE_COLLABORATOR = 'Remove collaborator'
export const THIS_ITEM = 'this item'
export const UNAUTHORIZED = 'You are unauthorized to perform this action'
export const UNKNOWN_ERROR = 'Unknown error occurred. Please try again'
export const USERNAME_NOT_FOUND = 'Username does not exist'
